/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imkimk;

import java.awt.Color;

/**
 *
 * @author ILHAM HADISYAH
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
        pPanjang pjg = new pPanjang();
        pSuhu sh = new pSuhu();
        pWaktu wkt = new pWaktu();
        pMassa ms = new pMassa();
        homePanel hp = new homePanel();
    public loginForm() {
        initComponents();
        setLocationRelativeTo(this);
        
        
        panelUtama.add(pjg);
        panelUtama.add(sh);
        panelUtama.add(wkt);
        panelUtama.add(ms);
        panelUtama.add(hp);
        
        hp.setVisible(true);
        pjg.setVisible(false);
        ms.setVisible(false);
        sh.setVisible(false);
        wkt.setVisible(false);
        
               
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panjang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        temp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(582, 491));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        panjang.setBackground(new java.awt.Color(255, 255, 255));
        panjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panjangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panjangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panjangMouseExited(evt);
            }
        });
        panjang.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/length.png"))); // NOI18N
        panjang.add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 80);

        jPanel1.add(panjang);
        panjang.setBounds(10, 10, 100, 100);

        masa.setBackground(new java.awt.Color(255, 255, 255));
        masa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masaMouseExited(evt);
            }
        });
        masa.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/mass.png"))); // NOI18N
        masa.add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 80);

        jPanel1.add(masa);
        masa.setBounds(10, 120, 100, 100);

        temp.setBackground(new java.awt.Color(255, 255, 255));
        temp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tempMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tempMouseExited(evt);
            }
        });
        temp.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/temp.png"))); // NOI18N
        temp.add(jLabel3);
        jLabel3.setBounds(10, 10, 80, 80);

        jPanel1.add(temp);
        temp.setBounds(10, 230, 100, 100);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeMouseExited(evt);
            }
        });
        time.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/time.png"))); // NOI18N
        time.add(jLabel4);
        jLabel4.setBounds(10, 10, 80, 80);

        jPanel1.add(time);
        time.setBounds(10, 340, 100, 100);

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel5.setText("KALKULATOR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 10, 270, 70);

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));
        panelUtama.setMinimumSize(new java.awt.Dimension(402, 309));
        panelUtama.setLayout(new javax.swing.BoxLayout(panelUtama, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(panelUtama);
        panelUtama.setBounds(130, 80, 410, 310);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/sign-out-alt.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 18));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(540, 450, 40, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImg/home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(500, 450, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void panjangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panjangMouseExited
        // TODO add your handling code here:
        panjang.setBackground(Color.white);
    }//GEN-LAST:event_panjangMouseExited

    private void panjangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panjangMouseEntered
        // TODO add your handling code here:
        panjang.setBackground(Color.red);
    }//GEN-LAST:event_panjangMouseEntered

    private void masaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaMouseEntered
        // TODO add your handling code here:
         masa.setBackground(Color.red);
    }//GEN-LAST:event_masaMouseEntered

    private void masaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaMouseExited
        // TODO add your handling code here:
         masa.setBackground(Color.white);
    }//GEN-LAST:event_masaMouseExited

    private void tempMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempMouseEntered
        // TODO add your handling code here:
        temp.setBackground(Color.red);
    }//GEN-LAST:event_tempMouseEntered

    private void tempMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempMouseExited
        // TODO add your handling code here:
        temp.setBackground(Color.white);
    }//GEN-LAST:event_tempMouseExited

    private void timeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseExited
        // TODO add your handling code here:
        time.setBackground(Color.white);
    }//GEN-LAST:event_timeMouseExited

    private void timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseEntered
        // TODO add your handling code here:
        time.setBackground(Color.red);
    }//GEN-LAST:event_timeMouseEntered

    private void panjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panjangMouseClicked
        // TODO add your handling code here:
        pjg.setVisible(true);
        ms.setVisible(false);
        sh.setVisible(false);
        wkt.setVisible(false);
        hp.setVisible(false);
        
    }//GEN-LAST:event_panjangMouseClicked

    private void masaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaMouseClicked
        // TODO add your handling code here:
        pjg.setVisible(false);
        ms.setVisible(true);
        sh.setVisible(false);
        wkt.setVisible(false);
        hp.setVisible(false);
       
    }//GEN-LAST:event_masaMouseClicked

    private void tempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempMouseClicked
        // TODO add your handling code here:
        pjg.setVisible(false);
        ms.setVisible(false);
        sh.setVisible(true);
        wkt.setVisible(false);
        hp.setVisible(false);
        
    }//GEN-LAST:event_tempMouseClicked

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        // TODO add your handling code here:
        pjg.setVisible(false);
        ms.setVisible(false);
        sh.setVisible(false);
        wkt.setVisible(true);
        hp.setVisible(false);
    }//GEN-LAST:event_timeMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(Color.red);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(Color.white);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        pjg.setVisible(false);
        ms.setVisible(false);
        sh.setVisible(false);
        wkt.setVisible(false);
        hp.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(175,209,255));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(Color.white);
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel masa;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel panjang;
    private javax.swing.JPanel temp;
    private javax.swing.JPanel time;
    // End of variables declaration//GEN-END:variables
}
