/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imkimk;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

/**
 *
 * @author ILHAM HADISYAH
 */
public class pMassa extends javax.swing.JPanel {

    /**
     * Creates new form pMassa
     */
    float inputan;
    
    public pMassa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMassa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isiInputan = new javax.swing.JTextField();
        pilihSatuan = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        kg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(402, 309));
        setLayout(null);

        paneMassa.setBackground(new java.awt.Color(255, 255, 255));
        paneMassa.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Konversi Berat");
        paneMassa.add(jLabel1);
        jLabel1.setBounds(90, 11, 209, 31);

        jLabel2.setText("Masukkan Angka : ");
        paneMassa.add(jLabel2);
        jLabel2.setBounds(10, 55, 110, 20);

        isiInputan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiInputanActionPerformed(evt);
            }
        });
        isiInputan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiInputanKeyTyped(evt);
            }
        });
        paneMassa.add(isiInputan);
        isiInputan.setBounds(120, 50, 69, 30);

        pilihSatuan.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pilihSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "hg", "dag", "g", "dg", "cg", "mg", " " }));
        paneMassa.add(pilihSatuan);
        pilihSatuan.setBounds(200, 50, 79, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        paneMassa.add(jButton1);
        jButton1.setBounds(290, 50, 63, 30);

        kg.setEditable(false);
        kg.setBackground(new java.awt.Color(255, 255, 255));
        kg.setBorder(null);
        paneMassa.add(kg);
        kg.setBounds(31, 133, 71, 14);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Kg");
        paneMassa.add(jLabel3);
        jLabel3.setBounds(112, 124, 21, 26);

        hg.setEditable(false);
        hg.setBackground(new java.awt.Color(255, 255, 255));
        hg.setBorder(null);
        paneMassa.add(hg);
        hg.setBounds(31, 170, 71, 14);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Hg");
        paneMassa.add(jLabel4);
        jLabel4.setBounds(112, 161, 24, 26);

        dag.setEditable(false);
        dag.setBackground(new java.awt.Color(255, 255, 255));
        dag.setBorder(null);
        paneMassa.add(dag);
        dag.setBounds(31, 207, 71, 14);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Dag");
        paneMassa.add(jLabel5);
        jLabel5.setBounds(112, 198, 32, 26);

        g.setEditable(false);
        g.setBackground(new java.awt.Color(255, 255, 255));
        g.setBorder(null);
        paneMassa.add(g);
        g.setBounds(31, 251, 71, 14);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("g");
        paneMassa.add(jLabel6);
        jLabel6.setBounds(112, 242, 10, 26);

        dg.setEditable(false);
        dg.setBackground(new java.awt.Color(255, 255, 255));
        dg.setBorder(null);
        paneMassa.add(dg);
        dg.setBounds(180, 133, 62, 14);
        paneMassa.add(jLabel7);
        jLabel7.setBounds(0, 0, 0, 0);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setText("Dg");
        paneMassa.add(jLabel8);
        jLabel8.setBounds(252, 124, 23, 26);

        cg.setEditable(false);
        cg.setBackground(new java.awt.Color(255, 255, 255));
        cg.setBorder(null);
        paneMassa.add(cg);
        cg.setBounds(180, 170, 62, 14);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setText("Cg");
        paneMassa.add(jLabel9);
        jLabel9.setBounds(252, 161, 21, 26);

        mg.setEditable(false);
        mg.setBackground(new java.awt.Color(255, 255, 255));
        mg.setBorder(null);
        paneMassa.add(mg);
        mg.setBounds(180, 207, 62, 14);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setText("Mg");
        paneMassa.add(jLabel10);
        jLabel10.setBounds(252, 198, 26, 26);

        add(paneMassa);
        paneMassa.setBounds(0, 0, 410, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void isiInputanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiInputanActionPerformed
        // TODO add your handling code here
        
      
    }//GEN-LAST:event_isiInputanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
         inputan = Float.parseFloat(isiInputan.getText().toString());
        if (pilihSatuan.getSelectedItem().equals("kg")) {
            kg.setText("" + inputan);
            hg.setText("" + inputan * 10);
            dag.setText("" + inputan * 100);
            g.setText("" + inputan * 1000);
            dg.setText("" + inputan * 10000);
            cg.setText("" + inputan * 100000);
            mg.setText("" + inputan * 1000000);
        } else if (pilihSatuan.getSelectedItem().equals("hg")) {
            kg.setText("" + inputan / 10);
            hg.setText("" + inputan);
            dag.setText("" + inputan * 10);
            g.setText("" + inputan * 100);
            dg.setText("" + inputan * 1000);
            cg.setText("" + inputan * 10000);
            mg.setText("" + inputan * 100000);
        } else if (pilihSatuan.getSelectedItem().equals("dag")) {
            kg.setText("" + inputan / 100);
            hg.setText("" + inputan / 10);
            dag.setText("" + inputan);
            g.setText("" + inputan * 10);
            dg.setText("" + inputan * 100);
            cg.setText("" + inputan * 1000);
            mg.setText("" + inputan * 10000);
        } else if (pilihSatuan.getSelectedItem().equals("g")) {
            kg.setText("" + inputan / 1000);
            hg.setText("" + inputan / 100);
            dag.setText("" + inputan / 10);
            g.setText("" + inputan);
            dg.setText("" + inputan * 10);
            cg.setText("" + inputan * 100);
            mg.setText("" + inputan * 1000);
        } else if (pilihSatuan.getSelectedItem().equals("dg")) {
            kg.setText("" + inputan / 10000);
            hg.setText("" + inputan / 1000);
            dag.setText("" + inputan / 100);
            g.setText("" + inputan / 10);
            dg.setText("" + inputan);
            cg.setText("" + inputan * 10);
            mg.setText("" + inputan * 100);
        
        } else if (pilihSatuan.getSelectedItem().equals("cg")) {
            kg.setText("" + inputan / 100000);
            hg.setText("" + inputan / 10000);
            dag.setText("" + inputan / 1000);
            g.setText("" + inputan / 100);
            dg.setText("" + inputan / 10);
            cg.setText("" + inputan);
            mg.setText("" + inputan * 10);
        }
        else if (pilihSatuan.getSelectedItem().equals("mg")) {
            kg.setText("" + inputan / 1000000);
            hg.setText("" + inputan / 100000);
            dag.setText("" + inputan / 10000);
            g.setText("" + inputan / 1000);
            dg.setText("" + inputan / 100);
            cg.setText("" + inputan / 10);
            mg.setText("" + inputan);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void isiInputanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiInputanKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_isiInputanKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cg;
    private javax.swing.JTextField dag;
    private javax.swing.JTextField dg;
    private javax.swing.JTextField g;
    private javax.swing.JTextField hg;
    private javax.swing.JTextField isiInputan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kg;
    private javax.swing.JTextField mg;
    private javax.swing.JPanel paneMassa;
    private javax.swing.JComboBox pilihSatuan;
    // End of variables declaration//GEN-END:variables
}
