/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imkimk;

/**
 *
 * @author ILHAM HADISYAH
 */
public class pSuhu extends javax.swing.JPanel {

    /**
     * Creates new form pSuhu
     */
    float inputan;
 
    
    public pSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isiInputan = new javax.swing.JTextField();
        pilihSatuan = new javax.swing.JComboBox();
        BOK = new javax.swing.JButton();
        fahrenhit = new javax.swing.JTextField();
        kelvin = new javax.swing.JTextField();
        celcius = new javax.swing.JTextField();
        reamur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(402, 309));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Konversi Suhu");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 10, 190, 30);

        jLabel2.setText("Masukkan Angka :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 70, 110, 30);

        isiInputan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiInputanActionPerformed(evt);
            }
        });
        isiInputan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiInputanKeyTyped(evt);
            }
        });
        jPanel2.add(isiInputan);
        isiInputan.setBounds(150, 70, 60, 30);

        pilihSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celcius", "Kelvin", "Reamur", "Farenhit" }));
        pilihSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihSatuanActionPerformed(evt);
            }
        });
        jPanel2.add(pilihSatuan);
        pilihSatuan.setBounds(220, 70, 65, 30);

        BOK.setText("OK");
        BOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOKActionPerformed(evt);
            }
        });
        jPanel2.add(BOK);
        BOK.setBounds(290, 70, 70, 30);

        fahrenhit.setEditable(false);
        fahrenhit.setBackground(new java.awt.Color(255, 255, 255));
        fahrenhit.setBorder(null);
        fahrenhit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenhitActionPerformed(evt);
            }
        });
        jPanel2.add(fahrenhit);
        fahrenhit.setBounds(210, 160, 90, 30);

        kelvin.setEditable(false);
        kelvin.setBackground(new java.awt.Color(255, 255, 255));
        kelvin.setBorder(null);
        kelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelvinActionPerformed(evt);
            }
        });
        jPanel2.add(kelvin);
        kelvin.setBounds(10, 160, 90, 29);

        celcius.setEditable(false);
        celcius.setBackground(new java.awt.Color(255, 255, 255));
        celcius.setBorder(null);
        jPanel2.add(celcius);
        celcius.setBounds(10, 110, 90, 29);

        reamur.setEditable(false);
        reamur.setBackground(new java.awt.Color(255, 255, 255));
        reamur.setBorder(null);
        jPanel2.add(reamur);
        reamur.setBounds(210, 110, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Celcius");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 110, 54, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kelvin");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 160, 54, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Reamur");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 110, 60, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fahrenhit");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(310, 160, 73, 22);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void isiInputanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiInputanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiInputanActionPerformed

    private void pilihSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihSatuanActionPerformed

    private void BOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOKActionPerformed
        // TODO add your handling code here:
        inputan = Float.parseFloat(isiInputan.getText().toString());
        if (pilihSatuan.getSelectedItem().equals("Celcius")){
            celcius.setText(""+inputan);
            kelvin.setText(""+(inputan +273.15));
            fahrenhit.setText(""+(inputan*1.8+32));
            reamur.setText(""+inputan*0.8);
        }
        else if(pilihSatuan.getSelectedItem().equals("Kelvin")){
            celcius.setText(""+(inputan-273.15));
            kelvin.setText(""+inputan);
            fahrenhit.setText(""+(inputan*1.8-459.67));
            reamur.setText(""+((inputan-273.15)*0.8));
            
    }
        else if(pilihSatuan.getSelectedItem().equals("Fahrenhit")){
            celcius.setText(""+((inputan-32)/1.8));
            kelvin.setText(""+((inputan+459.67)/1.8));
            fahrenhit.setText(""+inputan);
            reamur.setText(""+((inputan-32)*0.44));
            
    }
        else if(pilihSatuan.getSelectedItem().equals("Reamur")){
            celcius.setText(""+inputan/0.8);
            kelvin.setText(""+(inputan/0.8+237.15));
            fahrenhit.setText(""+(inputan*2.25+3));
            reamur.setText(""+inputan);
        }
        
        
    }//GEN-LAST:event_BOKActionPerformed

    private void fahrenhitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenhitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fahrenhitActionPerformed

    private void kelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelvinActionPerformed

    private void isiInputanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiInputanKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_isiInputanKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOK;
    private javax.swing.JTextField celcius;
    private javax.swing.JTextField fahrenhit;
    private javax.swing.JTextField isiInputan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kelvin;
    private javax.swing.JComboBox pilihSatuan;
    private javax.swing.JTextField reamur;
    // End of variables declaration//GEN-END:variables
}
